### ISSUE TITLE
wrong path for dtbo files

### ISSUE THREAD

**Issue by KoljaWindeler** [getchip/DIP-Docs#6]
Hi, the docu says:

put it in /lib/firmware/nextthing/chip/ to ensure the overlay is loaded on EEPROM detection.

that seams wrong, it should be /lib/firmware/nextthing**co**/chip/ if I'm right.
Also I had to add the w1_ds2431 to the autoload modules to get it working.
see https://bbs.nextthing.co/t/dip-device-autoload-on-boot-no-working/7671/15

Thanks Kolja

**Comment by nyboer** [comment]
Fixed, thanks for the note.
